// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Todo struct {
	ID          int64
	Title       string
	Description sql.NullString
	CategoryID  sql.NullInt64
	Severity    int64
	Done        sql.NullBool
	Archived    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
