// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTodo'](arg1, arg2, arg3);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
