// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTodo(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetTodos():Promise<Array<models.TodoResponse>>;

export function Greet(arg1:string):Promise<string>;
